package com.dimon.xcrm.dao;

import com.dimon.xcrm.pojo.XAddr;

public interface XAddrMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table X_ADDR
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table X_ADDR
     *
     * @mbggenerated
     */
    int insert(XAddr record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table X_ADDR
     *
     * @mbggenerated
     */
    int insertSelective(XAddr record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table X_ADDR
     *
     * @mbggenerated
     */
    XAddr selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table X_ADDR
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(XAddr record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table X_ADDR
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(XAddr record);
}