package com.dimon.xcrm.dao;

import com.dimon.xcrm.pojo.Xaddr;

public interface XaddrMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table XADDR
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long xaddrId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table XADDR
     *
     * @mbggenerated
     */
    int insert(Xaddr record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table XADDR
     *
     * @mbggenerated
     */
    int insertSelective(Xaddr record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table XADDR
     *
     * @mbggenerated
     */
    Xaddr selectByPrimaryKey(Long xaddrId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table XADDR
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Xaddr record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table XADDR
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Xaddr record);
}