package com.dimon.xcrm.dao;

import com.dimon.xcrm.pojo.XDic;

public interface XDicMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table X_DIC
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table X_DIC
     *
     * @mbggenerated
     */
    int insert(XDic record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table X_DIC
     *
     * @mbggenerated
     */
    int insertSelective(XDic record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table X_DIC
     *
     * @mbggenerated
     */
    XDic selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table X_DIC
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(XDic record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table X_DIC
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(XDic record);
}