package com.dimon.xcrm.dao;

import com.dimon.xcrm.pojo.Xdic;

public interface XdicMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table XDIC
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long xdicId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table XDIC
     *
     * @mbggenerated
     */
    int insert(Xdic record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table XDIC
     *
     * @mbggenerated
     */
    int insertSelective(Xdic record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table XDIC
     *
     * @mbggenerated
     */
    Xdic selectByPrimaryKey(Long xdicId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table XDIC
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Xdic record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table XDIC
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Xdic record);
}