package com.dimon.xcrm.dao;

import com.dimon.xcrm.pojo.XLogin;

public interface XLoginMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table X_LOGIN
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table X_LOGIN
     *
     * @mbggenerated
     */
    int insert(XLogin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table X_LOGIN
     *
     * @mbggenerated
     */
    int insertSelective(XLogin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table X_LOGIN
     *
     * @mbggenerated
     */
    XLogin selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table X_LOGIN
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(XLogin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table X_LOGIN
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(XLogin record);
}