package com.dimon.xcrm.dao;

import com.dimon.xcrm.pojo.Xuser;

public interface XuserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table XUSER
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long xuserId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table XUSER
     *
     * @mbggenerated
     */
    int insert(Xuser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table XUSER
     *
     * @mbggenerated
     */
    int insertSelective(Xuser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table XUSER
     *
     * @mbggenerated
     */
    Xuser selectByPrimaryKey(Long xuserId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table XUSER
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Xuser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table XUSER
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Xuser record);
    
    Xuser selectByAcctNo(String accTNo);
}