package com.dimon.xcrm.dao;

import com.dimon.xcrm.pojo.XUser;

public interface XUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table X_USER
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table X_USER
     *
     * @mbggenerated
     */
    int insert(XUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table X_USER
     *
     * @mbggenerated
     */
    int insertSelective(XUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table X_USER
     *
     * @mbggenerated
     */
    XUser selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table X_USER
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(XUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table X_USER
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(XUser record);

	XUser selectByAcccountNo(String accountNo);
}