package com.dimon.xcrm.pojo;

public class Xaddr {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column XADDR.XADDR_ID
     *
     * @mbggenerated
     */
    private Long xaddrId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column XADDR.XADDR_PROV
     *
     * @mbggenerated
     */
    private String xaddrProv;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column XADDR.XADDR_CTIY
     *
     * @mbggenerated
     */
    private String xaddrCtiy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column XADDR.XADDR_DIST
     *
     * @mbggenerated
     */
    private String xaddrDist;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column XADDR.XADDR_DETAIL
     *
     * @mbggenerated
     */
    private String xaddrDetail;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column XADDR.XADDR_TYPE
     *
     * @mbggenerated
     */
    private String xaddrType;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column XADDR.XADDR_ID
     *
     * @return the value of XADDR.XADDR_ID
     *
     * @mbggenerated
     */
    public Long getXaddrId() {
        return xaddrId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column XADDR.XADDR_ID
     *
     * @param xaddrId the value for XADDR.XADDR_ID
     *
     * @mbggenerated
     */
    public void setXaddrId(Long xaddrId) {
        this.xaddrId = xaddrId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column XADDR.XADDR_PROV
     *
     * @return the value of XADDR.XADDR_PROV
     *
     * @mbggenerated
     */
    public String getXaddrProv() {
        return xaddrProv;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column XADDR.XADDR_PROV
     *
     * @param xaddrProv the value for XADDR.XADDR_PROV
     *
     * @mbggenerated
     */
    public void setXaddrProv(String xaddrProv) {
        this.xaddrProv = xaddrProv == null ? null : xaddrProv.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column XADDR.XADDR_CTIY
     *
     * @return the value of XADDR.XADDR_CTIY
     *
     * @mbggenerated
     */
    public String getXaddrCtiy() {
        return xaddrCtiy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column XADDR.XADDR_CTIY
     *
     * @param xaddrCtiy the value for XADDR.XADDR_CTIY
     *
     * @mbggenerated
     */
    public void setXaddrCtiy(String xaddrCtiy) {
        this.xaddrCtiy = xaddrCtiy == null ? null : xaddrCtiy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column XADDR.XADDR_DIST
     *
     * @return the value of XADDR.XADDR_DIST
     *
     * @mbggenerated
     */
    public String getXaddrDist() {
        return xaddrDist;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column XADDR.XADDR_DIST
     *
     * @param xaddrDist the value for XADDR.XADDR_DIST
     *
     * @mbggenerated
     */
    public void setXaddrDist(String xaddrDist) {
        this.xaddrDist = xaddrDist == null ? null : xaddrDist.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column XADDR.XADDR_DETAIL
     *
     * @return the value of XADDR.XADDR_DETAIL
     *
     * @mbggenerated
     */
    public String getXaddrDetail() {
        return xaddrDetail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column XADDR.XADDR_DETAIL
     *
     * @param xaddrDetail the value for XADDR.XADDR_DETAIL
     *
     * @mbggenerated
     */
    public void setXaddrDetail(String xaddrDetail) {
        this.xaddrDetail = xaddrDetail == null ? null : xaddrDetail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column XADDR.XADDR_TYPE
     *
     * @return the value of XADDR.XADDR_TYPE
     *
     * @mbggenerated
     */
    public String getXaddrType() {
        return xaddrType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column XADDR.XADDR_TYPE
     *
     * @param xaddrType the value for XADDR.XADDR_TYPE
     *
     * @mbggenerated
     */
    public void setXaddrType(String xaddrType) {
        this.xaddrType = xaddrType == null ? null : xaddrType.trim();
    }
}