package com.dimon.xcrm.pojo;

public class XAddr {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column X_ADDR.ID
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column X_ADDR.PROV_ADDR
     *
     * @mbggenerated
     */
    private String provAddr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column X_ADDR.CTIY_ADDR
     *
     * @mbggenerated
     */
    private String ctiyAddr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column X_ADDR.DIST_ADDR
     *
     * @mbggenerated
     */
    private String distAddr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column X_ADDR.DETAIL_ADDR
     *
     * @mbggenerated
     */
    private String detailAddr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column X_ADDR.ADDR_TYPE
     *
     * @mbggenerated
     */
    private String addrType;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column X_ADDR.ID
     *
     * @return the value of X_ADDR.ID
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column X_ADDR.ID
     *
     * @param id the value for X_ADDR.ID
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column X_ADDR.PROV_ADDR
     *
     * @return the value of X_ADDR.PROV_ADDR
     *
     * @mbggenerated
     */
    public String getProvAddr() {
        return provAddr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column X_ADDR.PROV_ADDR
     *
     * @param provAddr the value for X_ADDR.PROV_ADDR
     *
     * @mbggenerated
     */
    public void setProvAddr(String provAddr) {
        this.provAddr = provAddr == null ? null : provAddr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column X_ADDR.CTIY_ADDR
     *
     * @return the value of X_ADDR.CTIY_ADDR
     *
     * @mbggenerated
     */
    public String getCtiyAddr() {
        return ctiyAddr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column X_ADDR.CTIY_ADDR
     *
     * @param ctiyAddr the value for X_ADDR.CTIY_ADDR
     *
     * @mbggenerated
     */
    public void setCtiyAddr(String ctiyAddr) {
        this.ctiyAddr = ctiyAddr == null ? null : ctiyAddr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column X_ADDR.DIST_ADDR
     *
     * @return the value of X_ADDR.DIST_ADDR
     *
     * @mbggenerated
     */
    public String getDistAddr() {
        return distAddr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column X_ADDR.DIST_ADDR
     *
     * @param distAddr the value for X_ADDR.DIST_ADDR
     *
     * @mbggenerated
     */
    public void setDistAddr(String distAddr) {
        this.distAddr = distAddr == null ? null : distAddr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column X_ADDR.DETAIL_ADDR
     *
     * @return the value of X_ADDR.DETAIL_ADDR
     *
     * @mbggenerated
     */
    public String getDetailAddr() {
        return detailAddr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column X_ADDR.DETAIL_ADDR
     *
     * @param detailAddr the value for X_ADDR.DETAIL_ADDR
     *
     * @mbggenerated
     */
    public void setDetailAddr(String detailAddr) {
        this.detailAddr = detailAddr == null ? null : detailAddr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column X_ADDR.ADDR_TYPE
     *
     * @return the value of X_ADDR.ADDR_TYPE
     *
     * @mbggenerated
     */
    public String getAddrType() {
        return addrType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column X_ADDR.ADDR_TYPE
     *
     * @param addrType the value for X_ADDR.ADDR_TYPE
     *
     * @mbggenerated
     */
    public void setAddrType(String addrType) {
        this.addrType = addrType == null ? null : addrType.trim();
    }
}