package com.dimon.xcrm.pojo;

public class Xdic {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column XDIC.XDIC_ID
     *
     * @mbggenerated
     */
    private Long xdicId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column XDIC.XDIC_TAB
     *
     * @mbggenerated
     */
    private String xdicTab;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column XDIC.XDIC_COL
     *
     * @mbggenerated
     */
    private String xdicCol;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column XDIC.XDIC_KEY
     *
     * @mbggenerated
     */
    private String xdicKey;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column XDIC.XDIC_VAL
     *
     * @mbggenerated
     */
    private String xdicVal;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column XDIC.XDIC_ID
     *
     * @return the value of XDIC.XDIC_ID
     *
     * @mbggenerated
     */
    public Long getXdicId() {
        return xdicId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column XDIC.XDIC_ID
     *
     * @param xdicId the value for XDIC.XDIC_ID
     *
     * @mbggenerated
     */
    public void setXdicId(Long xdicId) {
        this.xdicId = xdicId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column XDIC.XDIC_TAB
     *
     * @return the value of XDIC.XDIC_TAB
     *
     * @mbggenerated
     */
    public String getXdicTab() {
        return xdicTab;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column XDIC.XDIC_TAB
     *
     * @param xdicTab the value for XDIC.XDIC_TAB
     *
     * @mbggenerated
     */
    public void setXdicTab(String xdicTab) {
        this.xdicTab = xdicTab == null ? null : xdicTab.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column XDIC.XDIC_COL
     *
     * @return the value of XDIC.XDIC_COL
     *
     * @mbggenerated
     */
    public String getXdicCol() {
        return xdicCol;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column XDIC.XDIC_COL
     *
     * @param xdicCol the value for XDIC.XDIC_COL
     *
     * @mbggenerated
     */
    public void setXdicCol(String xdicCol) {
        this.xdicCol = xdicCol == null ? null : xdicCol.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column XDIC.XDIC_KEY
     *
     * @return the value of XDIC.XDIC_KEY
     *
     * @mbggenerated
     */
    public String getXdicKey() {
        return xdicKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column XDIC.XDIC_KEY
     *
     * @param xdicKey the value for XDIC.XDIC_KEY
     *
     * @mbggenerated
     */
    public void setXdicKey(String xdicKey) {
        this.xdicKey = xdicKey == null ? null : xdicKey.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column XDIC.XDIC_VAL
     *
     * @return the value of XDIC.XDIC_VAL
     *
     * @mbggenerated
     */
    public String getXdicVal() {
        return xdicVal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column XDIC.XDIC_VAL
     *
     * @param xdicVal the value for XDIC.XDIC_VAL
     *
     * @mbggenerated
     */
    public void setXdicVal(String xdicVal) {
        this.xdicVal = xdicVal == null ? null : xdicVal.trim();
    }
}