package com.dimon.xcrm.pojo;

public class XDic {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column X_DIC.ID
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column X_DIC.REL_TABLE
     *
     * @mbggenerated
     */
    private String relTable;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column X_DIC.REL_COL
     *
     * @mbggenerated
     */
    private String relCol;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column X_DIC.DIC_KEY
     *
     * @mbggenerated
     */
    private String dicKey;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column X_DIC.DIC_VALUE
     *
     * @mbggenerated
     */
    private String dicValue;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column X_DIC.ID
     *
     * @return the value of X_DIC.ID
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column X_DIC.ID
     *
     * @param id the value for X_DIC.ID
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column X_DIC.REL_TABLE
     *
     * @return the value of X_DIC.REL_TABLE
     *
     * @mbggenerated
     */
    public String getRelTable() {
        return relTable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column X_DIC.REL_TABLE
     *
     * @param relTable the value for X_DIC.REL_TABLE
     *
     * @mbggenerated
     */
    public void setRelTable(String relTable) {
        this.relTable = relTable == null ? null : relTable.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column X_DIC.REL_COL
     *
     * @return the value of X_DIC.REL_COL
     *
     * @mbggenerated
     */
    public String getRelCol() {
        return relCol;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column X_DIC.REL_COL
     *
     * @param relCol the value for X_DIC.REL_COL
     *
     * @mbggenerated
     */
    public void setRelCol(String relCol) {
        this.relCol = relCol == null ? null : relCol.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column X_DIC.DIC_KEY
     *
     * @return the value of X_DIC.DIC_KEY
     *
     * @mbggenerated
     */
    public String getDicKey() {
        return dicKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column X_DIC.DIC_KEY
     *
     * @param dicKey the value for X_DIC.DIC_KEY
     *
     * @mbggenerated
     */
    public void setDicKey(String dicKey) {
        this.dicKey = dicKey == null ? null : dicKey.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column X_DIC.DIC_VALUE
     *
     * @return the value of X_DIC.DIC_VALUE
     *
     * @mbggenerated
     */
    public String getDicValue() {
        return dicValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column X_DIC.DIC_VALUE
     *
     * @param dicValue the value for X_DIC.DIC_VALUE
     *
     * @mbggenerated
     */
    public void setDicValue(String dicValue) {
        this.dicValue = dicValue == null ? null : dicValue.trim();
    }
}