package com.dimon.xcrm.pojo;

import java.util.Date;

public class XLogin {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column X_LOGIN.ID
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column X_LOGIN.LOCAL_IP
     *
     * @mbggenerated
     */
    private String localIp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column X_LOGIN.INTERNET_IP
     *
     * @mbggenerated
     */
    private String internetIp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column X_LOGIN.LOGIN_TIME
     *
     * @mbggenerated
     */
    private Date loginTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column X_LOGIN.LOGOUT_TIME
     *
     * @mbggenerated
     */
    private Date logoutTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column X_LOGIN.IP_ADDR
     *
     * @mbggenerated
     */
    private String ipAddr;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column X_LOGIN.ID
     *
     * @return the value of X_LOGIN.ID
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column X_LOGIN.ID
     *
     * @param id the value for X_LOGIN.ID
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column X_LOGIN.LOCAL_IP
     *
     * @return the value of X_LOGIN.LOCAL_IP
     *
     * @mbggenerated
     */
    public String getLocalIp() {
        return localIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column X_LOGIN.LOCAL_IP
     *
     * @param localIp the value for X_LOGIN.LOCAL_IP
     *
     * @mbggenerated
     */
    public void setLocalIp(String localIp) {
        this.localIp = localIp == null ? null : localIp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column X_LOGIN.INTERNET_IP
     *
     * @return the value of X_LOGIN.INTERNET_IP
     *
     * @mbggenerated
     */
    public String getInternetIp() {
        return internetIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column X_LOGIN.INTERNET_IP
     *
     * @param internetIp the value for X_LOGIN.INTERNET_IP
     *
     * @mbggenerated
     */
    public void setInternetIp(String internetIp) {
        this.internetIp = internetIp == null ? null : internetIp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column X_LOGIN.LOGIN_TIME
     *
     * @return the value of X_LOGIN.LOGIN_TIME
     *
     * @mbggenerated
     */
    public Date getLoginTime() {
        return loginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column X_LOGIN.LOGIN_TIME
     *
     * @param loginTime the value for X_LOGIN.LOGIN_TIME
     *
     * @mbggenerated
     */
    public void setLoginTime(Date loginTime) {
        this.loginTime = loginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column X_LOGIN.LOGOUT_TIME
     *
     * @return the value of X_LOGIN.LOGOUT_TIME
     *
     * @mbggenerated
     */
    public Date getLogoutTime() {
        return logoutTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column X_LOGIN.LOGOUT_TIME
     *
     * @param logoutTime the value for X_LOGIN.LOGOUT_TIME
     *
     * @mbggenerated
     */
    public void setLogoutTime(Date logoutTime) {
        this.logoutTime = logoutTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column X_LOGIN.IP_ADDR
     *
     * @return the value of X_LOGIN.IP_ADDR
     *
     * @mbggenerated
     */
    public String getIpAddr() {
        return ipAddr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column X_LOGIN.IP_ADDR
     *
     * @param ipAddr the value for X_LOGIN.IP_ADDR
     *
     * @mbggenerated
     */
    public void setIpAddr(String ipAddr) {
        this.ipAddr = ipAddr == null ? null : ipAddr.trim();
    }
}