package com.dimon.xcrm.pojo;

import java.util.Date;

import javax.validation.constraints.NotNull;

public class XUser {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column X_USER.ID
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column X_USER.NAME
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column X_USER.REAL_NAME
     *
     * @mbggenerated
     */
    private String realName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column X_USER.ACCOUNT_NO
     *
     * @mbggenerated
     */
    @NotNull
    private String accountNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column X_USER.PWD
     *
     * @mbggenerated
     */
    private String pwd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column X_USER.EMAIL
     *
     * @mbggenerated
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column X_USER.MOBILE_PHONE
     *
     * @mbggenerated
     */
    private Long mobilePhone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column X_USER.ADDR_ID
     *
     * @mbggenerated
     */
    private Long addrId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column X_USER.LAST_LOGIN
     *
     * @mbggenerated
     */
    private Date lastLogin;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column X_USER.ID
     *
     * @return the value of X_USER.ID
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column X_USER.ID
     *
     * @param id the value for X_USER.ID
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column X_USER.NAME
     *
     * @return the value of X_USER.NAME
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column X_USER.NAME
     *
     * @param name the value for X_USER.NAME
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column X_USER.REAL_NAME
     *
     * @return the value of X_USER.REAL_NAME
     *
     * @mbggenerated
     */
    public String getRealName() {
        return realName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column X_USER.REAL_NAME
     *
     * @param realName the value for X_USER.REAL_NAME
     *
     * @mbggenerated
     */
    public void setRealName(String realName) {
        this.realName = realName == null ? null : realName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column X_USER.ACCOUNT_NO
     *
     * @return the value of X_USER.ACCOUNT_NO
     *
     * @mbggenerated
     */
    public String getAccountNo() {
        return accountNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column X_USER.ACCOUNT_NO
     *
     * @param accountNo the value for X_USER.ACCOUNT_NO
     *
     * @mbggenerated
     */
    public void setAccountNo(String accountNo) {
        this.accountNo = accountNo == null ? null : accountNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column X_USER.PWD
     *
     * @return the value of X_USER.PWD
     *
     * @mbggenerated
     */
    public String getPwd() {
        return pwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column X_USER.PWD
     *
     * @param pwd the value for X_USER.PWD
     *
     * @mbggenerated
     */
    public void setPwd(String pwd) {
        this.pwd = pwd == null ? null : pwd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column X_USER.EMAIL
     *
     * @return the value of X_USER.EMAIL
     *
     * @mbggenerated
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column X_USER.EMAIL
     *
     * @param email the value for X_USER.EMAIL
     *
     * @mbggenerated
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column X_USER.MOBILE_PHONE
     *
     * @return the value of X_USER.MOBILE_PHONE
     *
     * @mbggenerated
     */
    public Long getMobilePhone() {
        return mobilePhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column X_USER.MOBILE_PHONE
     *
     * @param mobilePhone the value for X_USER.MOBILE_PHONE
     *
     * @mbggenerated
     */
    public void setMobilePhone(Long mobilePhone) {
        this.mobilePhone = mobilePhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column X_USER.ADDR_ID
     *
     * @return the value of X_USER.ADDR_ID
     *
     * @mbggenerated
     */
    public Long getAddrId() {
        return addrId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column X_USER.ADDR_ID
     *
     * @param addrId the value for X_USER.ADDR_ID
     *
     * @mbggenerated
     */
    public void setAddrId(Long addrId) {
        this.addrId = addrId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column X_USER.LAST_LOGIN
     *
     * @return the value of X_USER.LAST_LOGIN
     *
     * @mbggenerated
     */
    public Date getLastLogin() {
        return lastLogin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column X_USER.LAST_LOGIN
     *
     * @param lastLogin the value for X_USER.LAST_LOGIN
     *
     * @mbggenerated
     */
    public void setLastLogin(Date lastLogin) {
        this.lastLogin = lastLogin;
    }
}