package com.dimon.xcrm.pojo;

import java.util.Date;

public class Xuser {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column XUSER.XUSER_ID
     *
     * @mbggenerated
     */
    private Long xuserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column XUSER.XUSER_NAME
     *
     * @mbggenerated
     */
    private String xuserName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column XUSER.XUSER_REALNAME
     *
     * @mbggenerated
     */
    private String xuserRealname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column XUSER.XUSER_ACCTNO
     *
     * @mbggenerated
     */
    private String xuserAcctno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column XUSER.XUSER_PWD
     *
     * @mbggenerated
     */
    private String xuserPwd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column XUSER.XUSER_EMAIL
     *
     * @mbggenerated
     */
    private String xuserEmail;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column XUSER.XUSER_MPHONE
     *
     * @mbggenerated
     */
    private String xuserMphone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column XUSER.XUSER_ADDRID
     *
     * @mbggenerated
     */
    private Long xuserAddrid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column XUSER.XUSER_LASTLOGIN
     *
     * @mbggenerated
     */
    private Date xuserLastlogin;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column XUSER.XUSER_ID
     *
     * @return the value of XUSER.XUSER_ID
     *
     * @mbggenerated
     */
    public Long getXuserId() {
        return xuserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column XUSER.XUSER_ID
     *
     * @param xuserId the value for XUSER.XUSER_ID
     *
     * @mbggenerated
     */
    public void setXuserId(Long xuserId) {
        this.xuserId = xuserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column XUSER.XUSER_NAME
     *
     * @return the value of XUSER.XUSER_NAME
     *
     * @mbggenerated
     */
    public String getXuserName() {
        return xuserName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column XUSER.XUSER_NAME
     *
     * @param xuserName the value for XUSER.XUSER_NAME
     *
     * @mbggenerated
     */
    public void setXuserName(String xuserName) {
        this.xuserName = xuserName == null ? null : xuserName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column XUSER.XUSER_REALNAME
     *
     * @return the value of XUSER.XUSER_REALNAME
     *
     * @mbggenerated
     */
    public String getXuserRealname() {
        return xuserRealname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column XUSER.XUSER_REALNAME
     *
     * @param xuserRealname the value for XUSER.XUSER_REALNAME
     *
     * @mbggenerated
     */
    public void setXuserRealname(String xuserRealname) {
        this.xuserRealname = xuserRealname == null ? null : xuserRealname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column XUSER.XUSER_ACCTNO
     *
     * @return the value of XUSER.XUSER_ACCTNO
     *
     * @mbggenerated
     */
    public String getXuserAcctno() {
        return xuserAcctno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column XUSER.XUSER_ACCTNO
     *
     * @param xuserAcctno the value for XUSER.XUSER_ACCTNO
     *
     * @mbggenerated
     */
    public void setXuserAcctno(String xuserAcctno) {
        this.xuserAcctno = xuserAcctno == null ? null : xuserAcctno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column XUSER.XUSER_PWD
     *
     * @return the value of XUSER.XUSER_PWD
     *
     * @mbggenerated
     */
    public String getXuserPwd() {
        return xuserPwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column XUSER.XUSER_PWD
     *
     * @param xuserPwd the value for XUSER.XUSER_PWD
     *
     * @mbggenerated
     */
    public void setXuserPwd(String xuserPwd) {
        this.xuserPwd = xuserPwd == null ? null : xuserPwd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column XUSER.XUSER_EMAIL
     *
     * @return the value of XUSER.XUSER_EMAIL
     *
     * @mbggenerated
     */
    public String getXuserEmail() {
        return xuserEmail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column XUSER.XUSER_EMAIL
     *
     * @param xuserEmail the value for XUSER.XUSER_EMAIL
     *
     * @mbggenerated
     */
    public void setXuserEmail(String xuserEmail) {
        this.xuserEmail = xuserEmail == null ? null : xuserEmail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column XUSER.XUSER_MPHONE
     *
     * @return the value of XUSER.XUSER_MPHONE
     *
     * @mbggenerated
     */
    public String getXuserMphone() {
        return xuserMphone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column XUSER.XUSER_MPHONE
     *
     * @param xuserMphone the value for XUSER.XUSER_MPHONE
     *
     * @mbggenerated
     */
    public void setXuserMphone(String xuserMphone) {
        this.xuserMphone = xuserMphone == null ? null : xuserMphone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column XUSER.XUSER_ADDRID
     *
     * @return the value of XUSER.XUSER_ADDRID
     *
     * @mbggenerated
     */
    public Long getXuserAddrid() {
        return xuserAddrid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column XUSER.XUSER_ADDRID
     *
     * @param xuserAddrid the value for XUSER.XUSER_ADDRID
     *
     * @mbggenerated
     */
    public void setXuserAddrid(Long xuserAddrid) {
        this.xuserAddrid = xuserAddrid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column XUSER.XUSER_LASTLOGIN
     *
     * @return the value of XUSER.XUSER_LASTLOGIN
     *
     * @mbggenerated
     */
    public Date getXuserLastlogin() {
        return xuserLastlogin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column XUSER.XUSER_LASTLOGIN
     *
     * @param xuserLastlogin the value for XUSER.XUSER_LASTLOGIN
     *
     * @mbggenerated
     */
    public void setXuserLastlogin(Date xuserLastlogin) {
        this.xuserLastlogin = xuserLastlogin;
    }
}